### final_df에서 동명이인 뽑기

In [48]:
import collections

In [52]:
final_df = pd.read_csv("../final_df_public.csv")

In [53]:
final_df = final_df.drop("Unnamed: 0", axis=1)
final_df

,id,영화명,감독,제작사,수입사,배급사,개봉일,영화유형,영화형태,국적,...,서울매출액,서울관객수,장르,등급,영화구분,expert_rating,starring_actors,running_times,audience_rating,rating_audiences
0,0,어벤져스: 에이지 오브 울트론,조스 웨던,NaN,월트디즈니컴퍼니코리아(주),월트디즈니컴퍼니코리아(주),2015-04-23,개봉영화,장편,미국,...,25001906266,2823388,액션,12세이상관람가,일반영화,6.92,"로버트 다우니 주니어(토니 스타크 / 아이언맨), 크리스 헴스워스(토르), 마크 러...",141분,8.612376613515565,5268
1,1,국제시장,윤제균,"(주)제이케이필름,씨제이이앤엠(주)",NaN,씨제이이앤엠(주),2014-12-17,개봉영화,장편,한국,...,16331193634,2033863,드라마,12세이상관람가,일반영화,5.81,"황정민(덕수), 김윤진(영자), 오달수(달구)",126분,9.272090988626422,1143
2,2,킹스맨 : 시크릿 에이전트,매튜 본,NaN,이십세기폭스코리아(주),이십세기폭스코리아(주),2015-02-11,개봉영화,장편,미국,...,16707645195,1968882,액션,청소년관람불가,일반영화,7.58,"콜린 퍼스(해리), 태런 에저튼(에그시), 사무엘 L. 잭슨(발렌타인)",128분,8.96078431372549,918
3,3,쥬라기 월드,콜린 트레보로우,NaN,유니버설픽쳐스인터내셔널 코리아(유),유니버설픽쳐스인터내셔널 코리아(유),2015-06-11,개봉영화,장편,미국,...,11510753371,1243034,액션,12세이상관람가,일반영화,6.63,"크리스 프랫, 브라이스 달라스 하워드, 빈센트 도노프리오",125분,8.337789203084833,1945
4,4,조선명탐정 : 사라진 놉의 딸,김석윤,청년필름(주),NaN,(주)쇼박스,2015-02-11,개봉영화,장편,한국,...,6908501928,845522,사극,12세이상관람가,일반영화,5.85,"김명민(명탐정 김민), 오달수(서필), 이연희(히사코)",125분,8.172131147540984,610
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
923,923,프란치스코 교황 : 맨 오브 히스 워드,빔 벤더스,NaN,㈜영화사 백두대간,"㈜영화사 백두대간,영화사 풀",2019-11-21,개봉영화,장편,이탈리아,...,55059980,6840,다큐멘터리,전체관람가,독립/예술영화,6.33,프란치스코(본인),96분,9.6,10
924,924,아이리시맨,마틴 스코세이지,NaN,NaN,판씨네마(주),2019-11-20,개봉영화,장편,미국,...,215547620,24855,범죄,청소년관람불가,독립/예술영화,9.11,"로버트 드 니로, 알 파치노, 조 페시",209분,8.870588235294118,85
925,925,빅 위시,NaN,NaN,(주)박수엔터테인먼트,(주)박수엔터테인먼트,2019-10-30,개봉영화,장편,멕시코,...,42956220,5227,판타지,전체관람가,일반영화,6.00,[국내] 전체 관람가,79분,6.5,4
926,926,너를 만난 여름,장적사,NaN,오드,"오드,(주)홈초이스",2019-10-16,개봉영화,장편,중국,...,100555600,11619,드라마,12세이상관람가,독립/예술영화,5.50,"진비우(위화이), 하람두(겅겅)",109분,8.428571428571429,63
927,927,100일 동안 100가지로 100퍼센트 행복찾기,플로리안 데이비드 핏츠,NaN,(주)영화사 진진,(주)영화사 진진,2019-09-12,개봉영화,장편,독일,...,160852490,19490,코미디,15세이상관람가,독립/예술영화,5.50,"플로리안 데이비드 핏츠(폴), 마치아스 슈와바이어퍼(토니)",111분,8.962962962962964,27

In [54]:
starring_actors_list  = list(final_df["starring_actors"])

In [55]:
name_list = []

for names in starring_actors_list:
    pre_list = names.split(',')
    for name in pre_list:
        name_list.append(name.split('(')[0].strip())

In [76]:
len(name_list)

2490

In [77]:
duplicated_actors = list([name for name, count in collections.Counter(name_list).items() if count > 1])

In [78]:
len(duplicated_actors)

490

In [79]:
duplicated_actors[10]

'브라이스 달라스 하워드'

In [110]:
def find_duplicated(duplicated_actors, final_df, col = "starring_actors"):
    ls_m = []
    for actor in duplicated_actors:
        for i in range(len(final_df)):
            if actor in final_df[col][i]:
                ls_m.append({"actor" : actor, "idx" : i, "영화명" : final_df["영화명"][i]})
    return pd.DataFrame(ls_m)

In [112]:
actor_df = find_duplicated(["로버트 다우니 주니어", "크리스 헴스워스"], final_df)
actor_df

          actor  idx               영화명
0   로버트 다우니 주니어    0  어벤져스: 에이지 오브 울트론
1   로버트 다우니 주니어  196     캡틴 아메리카: 시빌 워
2   로버트 다우니 주니어  563      어벤져스: 인피니티 워
3   로버트 다우니 주니어  748        어벤져스: 엔드게임
4      크리스 헴스워스    0  어벤져스: 에이지 오브 울트론
5      크리스 헴스워스  126         하트 오브 더 씨
6      크리스 헴스워스  230        헌츠맨: 윈터스 워
7      크리스 헴스워스  477         토르: 라그나로크
8      크리스 헴스워스  563      어벤져스: 인피니티 워
9      크리스 헴스워스  607            12 솔져스
10     크리스 헴스워스  748        어벤져스: 엔드게임
11     크리스 헴스워스  770     맨 인 블랙: 인터내셔널

In [81]:
final_df["duplicated"] = final_df["starring_actors"].apply(find_duplicated)

TypeError: list indices must be integers or slices, not str

In [61]:
final_df

,id,영화명,감독,제작사,수입사,배급사,개봉일,영화유형,영화형태,국적,...,서울관객수,장르,등급,영화구분,expert_rating,starring_actors,running_times,audience_rating,rating_audiences,duplicated
0,0,어벤져스: 에이지 오브 울트론,조스 웨던,NaN,월트디즈니컴퍼니코리아(주),월트디즈니컴퍼니코리아(주),2015-04-23,개봉영화,장편,미국,...,2823388,액션,12세이상관람가,일반영화,6.92,"로버트 다우니 주니어(토니 스타크 / 아이언맨), 크리스 헴스워스(토르), 마크 러...",141분,8.612376613515565,5268,unique
1,1,국제시장,윤제균,"(주)제이케이필름,씨제이이앤엠(주)",NaN,씨제이이앤엠(주),2014-12-17,개봉영화,장편,한국,...,2033863,드라마,12세이상관람가,일반영화,5.81,"황정민(덕수), 김윤진(영자), 오달수(달구)",126분,9.272090988626422,1143,unique
2,2,킹스맨 : 시크릿 에이전트,매튜 본,NaN,이십세기폭스코리아(주),이십세기폭스코리아(주),2015-02-11,개봉영화,장편,미국,...,1968882,액션,청소년관람불가,일반영화,7.58,"콜린 퍼스(해리), 태런 에저튼(에그시), 사무엘 L. 잭슨(발렌타인)",128분,8.96078431372549,918,unique
3,3,쥬라기 월드,콜린 트레보로우,NaN,유니버설픽쳐스인터내셔널 코리아(유),유니버설픽쳐스인터내셔널 코리아(유),2015-06-11,개봉영화,장편,미국,...,1243034,액션,12세이상관람가,일반영화,6.63,"크리스 프랫, 브라이스 달라스 하워드, 빈센트 도노프리오",125분,8.337789203084833,1945,unique
4,4,조선명탐정 : 사라진 놉의 딸,김석윤,청년필름(주),NaN,(주)쇼박스,2015-02-11,개봉영화,장편,한국,...,845522,사극,12세이상관람가,일반영화,5.85,"김명민(명탐정 김민), 오달수(서필), 이연희(히사코)",125분,8.172131147540984,610,unique
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
923,923,프란치스코 교황 : 맨 오브 히스 워드,빔 벤더스,NaN,㈜영화사 백두대간,"㈜영화사 백두대간,영화사 풀",2019-11-21,개봉영화,장편,이탈리아,...,6840,다큐멘터리,전체관람가,독립/예술영화,6.33,프란치스코(본인),96분,9.6,10,unique
924,924,아이리시맨,마틴 스코세이지,NaN,NaN,판씨네마(주),2019-11-20,개봉영화,장편,미국,...,24855,범죄,청소년관람불가,독립/예술영화,9.11,"로버트 드 니로, 알 파치노, 조 페시",209분,8.870588235294118,85,unique
925,925,빅 위시,NaN,NaN,(주)박수엔터테인먼트,(주)박수엔터테인먼트,2019-10-30,개봉영화,장편,멕시코,...,5227,판타지,전체관람가,일반영화,6.00,[국내] 전체 관람가,79분,6.5,4,unique
926,926,너를 만난 여름,장적사,NaN,오드,"오드,(주)홈초이스",2019-10-16,개봉영화,장편,중국,...,11619,드라마,12세이상관람가,독립/예술영화,5.50,"진비우(위화이), 하람두(겅겅)",109분,8.428571428571429,63,unique
927,927,100일 동안 100가지로 100퍼센트 행복찾기,플로리안 데이비드 핏츠,NaN,(주)영화사 진진,(주)영화사 진진,2019-09-12,개봉영화,장편,독일,...,19490,코미디,15세이상관람가,독립/예술영화,5.50,"플로리안 데이비드 핏츠(폴), 마치아스 슈와바이어퍼(토니)",111분,8.962962962962964,27,unique