In [126]:
final_df = pd.read_csv("final_df_09.csv").drop(columns='Unnamed: 0')
compare_df = pd.read_csv("director_compare_df.csv").drop(columns='Unnamed: 0')
compare_df2 = pd.read_csv("actor_compare_df.csv").drop(columns='Unnamed: 0')
compare_df_sep = pd.read_csv("director_compare_df_sep_d.csv").drop(columns='Unnamed: 0')
compare_df2_sep = pd.read_csv("actor_compare_df_sep_d.csv").drop(columns='Unnamed: 0')

In [128]:
# for i, row in final_df.iterrows():
#     if row['director_power'] > row['aud_nationwide']:
#         print(row['director'])

In [129]:
len(final_df)

925

In [136]:
len(compare_df_sep)

1422

In [137]:
len(compare_df2_sep)

1671

In [143]:
final_df.columns

Index(['title', 'director', 'distributor', 'distributor_group', 'release_date',
       'release_season', 'nation', 'screen', 'genre', 'rate', 'expert_rating',
       'starring_actors', 'running_times', 'audience_rating',
       'rating_audiences', 'director_power', 'sequel', 'original',
       'actor_power', 'before_news', 'after_news', 'aud_nationwide'],
      dtype='object')

In [213]:
final_df = pd.read_csv("../final_df_08.csv").drop(columns=['Unnamed: 0', 'director_movie_num'])

In [216]:
final_df

,title,director,distributor,distributor_group,release_date,release_season,release,form,nation,screen,...,expert_rating,starring_actors,running_times,audience_rating,rating_audiences,realease_year,director_power,sequel,original,actor_power
0,어벤져스: 에이지 오브 울트론,조스 웨던,월트디즈니컴퍼니코리아(주),B,4/23/2015,spring,개봉영화,장편,미국,1843,...,6.92,"로버트 다우니 주니어,크리스 헴스워스,마크 러팔로",141,8.612377,5268,2015,17567536.0,1,0,542407997
1,국제시장,윤제균,씨제이이앤엠(주),A,12/17/2014,winter,개봉영화,장편,한국,966,...,5.81,"황정민,김윤진,오달수",126,9.272091,1143,2014,5334561.0,0,0,608444941
2,킹스맨 : 시크릿 에이전트,매튜 본,이십세기폭스코리아(주),B,2/11/2015,winter,개봉영화,장편,미국,706,...,7.58,"콜린 퍼스,태런 에저튼,사무엘 L. 잭슨",128,8.960784,918,2015,17202955.0,1,0,319404847
3,쥬라기 월드,콜린 트레보로우,유니버설픽쳐스인터내셔널 코리아(유),B,6/11/2015,summer,개봉영화,장편,미국,1290,...,6.63,"크리스 프랫,브라이스 달라스 하워드,빈센트 도노프리오",125,8.337789,1945,2015,4565911.0,0,1,110571787
4,조선명탐정 : 사라진 놉의 딸,김석윤,(주)쇼박스,C,2/11/2015,winter,개봉영화,장편,한국,811,...,5.85,"김명민,오달수,이연희",125,8.172131,610,2015,10168360.0,1,0,297483438
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
920,프란치스코 교황 : 맨 오브 히스 워드,빔 벤더스,"㈜영화사 백두대간,영화사 풀",D,11/21/2019,autumn,개봉영화,장편,기타,54,...,6.33,프란치스코,96,9.600000,10,2019,37282.0,0,1,0
921,아이리시맨,마틴 스코세이지,판씨네마(주),D,11/20/2019,autumn,개봉영화,장편,미국,68,...,9.11,"로버트 드 니로,알 파치노,조 페시",209,8.870588,85,2019,809305.0,0,1,51829915
922,빅 위시,카를로스 구티에레스 메드라노,(주)박수엔터테인먼트,D,10/30/2019,autumn,개봉영화,장편,기타,336,...,6.00,-,79,6.500000,4,2019,0.0,0,0,0
923,너를 만난 여름,장적사,"오드,(주)홈초이스",D,10/16/2019,autumn,개봉영화,장편,기타,174,...,5.50,"진비우,하람두",109,8.428571,63,2019,31888.0,0,0,0
924,100일 동안 100가지로 100퍼센트 행복찾기,플로리안 데이비드 핏츠,(주)영화사 진진,D,9/12/2019,autumn,개봉영화,장편,기타,37,...,5.50,"플로리안 데이비드 핏츠,마치아스 슈와바이어퍼",111,8.962963,27,2019,31866.0,0,0,0

In [248]:
date_list = []

for i, row in final_df.iterrows():
        date_list.append(row['release_date'][-4:])

In [249]:
# for date in date_list:
#     if len(date) != 4:
#         print(date)

In [250]:
# 감독파워 측정함수(compare_df_sep)

index = 0
director_count_list = []
movie_count_list = []

def director_func(director):
    global index
    
    total_audience = 0
    movie_num = 0
    director_list = director.split(",")
    limit_date = int(date_list[index]) - 3
    
    if len(director_list) > 1:
        director_count_list.append(len(director_list))
        for director_name in director_list:
            for i, row in compare_df_sep.iterrows():
                if director_name in row['감독'].split(","):
                    if int(date_list[index]) > int(row['개봉일'][:4]) >= limit_date:
                        total_audience += row['전국관객수']
                        movie_num += 1
    else: 
        director_count_list.append(1)
        for i, row in compare_df_sep.iterrows():
            if director_list[0] in row['감독'].split(","):
                if int(date_list[index]) > int(row['개봉일'][:4]) >= limit_date:
                    total_audience += row['전국관객수']
                    movie_num += 1
            
    index += 1
    movie_count_list.append(movie_num)
    
    return total_audience

In [255]:
final_df['director_power'] = final_df['director'].apply(director_func)

In [256]:
final_df['director_count'] = director_count_list

In [272]:
final_df['director_movie_count'] = movie_count_list

In [278]:
final_df.to_csv('final_df_10.csv')

In [264]:
# compare_df_sep[compare_df_sep['감독'] == '매튜 본']

In [288]:
date_list = []

for i, row in final_df.iterrows():
        date_list.append(row['release_date'][-4:])

In [289]:
# 배우 성과측정 함수 (compare_df2_sep)

index = 0
actor_involved_movie_count_list = []

def actor_func(actors):
    global index
    
    total_audience = 0
    movie_count = 0
    actor_list = actors.split(",")
    limit_date = int(date_list[index]) - 3
    
    for each_actor in actor_list:
        for i, row in compare_df2_sep.iterrows():
            if each_actor in row['배우'].split(","):
                if int(date_list[index]) > int(row['개봉일'][:4]) >= limit_date:
                    total_audience += row['전국관객수']
                    movie_count += 1
        
    index += 1
    actor_involved_movie_count_list.append(movie_count)
    
    return total_audience

In [290]:
final_df['actor_power'] = final_df['starring_actors'].apply(actor_func)

In [293]:
final_df['actor_movie_count'] = actor_involved_movie_count_list

In [280]:
compare_df2_sep

,영화명,개봉일,매출액,매출액점유율,누적매출액,관객수,누적관객수,스크린수,상영횟수,대표국적,...,제작사,배급사,등급,장르,감독,배우,main_actors,개봉일_int,actor_involved,전국관객수
0,어벤져스,2012-04-26,59546521565,0.093,59546521565,7073037,7073037,967,109646,미국,...,NaN,한국소니픽쳐스릴리징브에나비스타영화㈜,12세이상관람가,"액션,SF",조스 웨던,"로버트 다우니 주니어,스칼렛 요한슨,크리스 헴스워스,크리스 에반스,제레미 레너","로버트 다우니 주니어, 스칼렛 요한슨, 크리스 헴스워스",2012,True,7073037
1,범죄와의 전쟁: 나쁜놈들 전성시대,2012-02-02,36538823500,0.057,36538823500,4719872,4719872,713,91889,한국,...,"(주)팔레트픽처스,(주)쇼박스",(주)쇼박스,청소년관람불가,"범죄,드라마",윤종빈,"최민식,하정우,조진웅,마동석,곽도원,김성균,박성광,이철민,임자연,임헌호,권종현,김민...","최민식, 하정우, 조진웅",2012,True,4710454
2,내 아내의 모든 것,2012-05-17,32518413000,0.051,32518413000,4360205,4360205,563,82867,한국,...,"(주)수필름,영화사 집",(주)넥스트엔터테인먼트월드(NEW),15세이상관람가,"코미디,멜로/로맨스",민규동,"임수정,이선균,류승룡,이달형,이진희,김도균,김선일,최차원,신경철,옥광희,박희본,김지...","임수정, 이선균, 류승룡",2012,True,4360205
3,댄싱퀸,2012-01-18,30129331500,0.047,30129331500,4057555,4057555,544,80969,한국,...,"(주)제이케이필름,씨제이이앤엠(주)",씨제이이앤엠(주),12세이상관람가,"코미디,드라마",이석훈,"황정민,엄정화,정성화,오나라,박정민,박사랑,임호걸,정원영,이정건,안은정,라미란,송원...","황정민, 엄정화, 정성화",2012,True,4057546
4,부러진 화살,2012-01-18,25878110500,0.040,25936754000,3450941,3459780,530,71556,한국,...,(주)아우라픽처스,(주)넥스트엔터테인먼트월드(NEW),15세이상관람가,드라마,정지영,"안성기,박원상,나영희,김지호,이승훈,이춘연,이홍표,임태연,장길수,장현남,전윤희,조세...","안성기, 박원상, 나영희",2012,True,3450941
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1666,앳 퍼스트 라이트,2019-09-25,650700,0.000,650700,89,89,8,49,캐나다,...,NaN,이언픽쳐스,12세이상관람가,"드라마,SF,스릴러",제이슨 스톤,"스테파니 스콧,테오도르 펠르랭,세이드 타그마오우이","스테파니 스콧, 테오도르 펠르랭, 세이드 타그마오우이",2019,True,89
1667,액츠 오브 바이올런스,2019-07-15,403000,0.000,403000,71,71,20,71,미국,...,NaN,(주)누리픽쳐스,청소년관람불가,"액션,드라마",브렛 도노후,"브루스 윌리스,콜 하우저,애쉬튼 홈즈,멜리사 볼로나,숀 애쉬모어","브루스 윌리스, 콜 하우저, 애쉬튼 홈즈",2019,True,71
1668,먹거나 먹히거나,2019-10-10,44000,0.000,44000,18,18,5,18,미국,...,NaN,㈜코리아스크린,청소년관람불가,"액션,범죄,드라마",폴 슈레이더,"니콜라스 케이지,윌렘 데포,루이자 크로즈,폴 슈레이더","니콜라스 케이지, 윌렘 데포, 루이자 크로즈",2019,True,18
1669,백트레이스,2019-07-30,1000,0.000,1000,1,1,1,1,미국,...,NaN,주식회사 풍경소리,15세이상관람가,"액션,스릴러",브라이언 A 밀러,"실베스터 스탤론,라이언 구즈만,매튜 모딘","실베스터 스탤론, 라이언 구즈만, 매튜 모딘",2019,True,1
1670,크리미널 : 해튼가든,2019-11-21,1000,0.000,1000,1,1,1,1,영국,...,워킹 타이틀 필름,주식회사 세미콜론스튜디오,15세이상관람가,"범죄,드라마",제임스 마쉬,"마이클 케인,짐 브로드벤트,찰리 콕스","마이클 케인, 짐 브로드벤트, 찰리 콕스",2019,True,1

In [294]:
final_df

,title,director,distributor,distributor_group,release_date,release_season,release,form,nation,screen,...,audience_rating,rating_audiences,realease_year,director_power,sequel,original,actor_power,director_count,director_movie_count,actor_movie_count
0,어벤져스: 에이지 오브 울트론,조스 웨던,월트디즈니컴퍼니코리아(주),B,4/23/2015,spring,개봉영화,장편,미국,1843,...,8.612377,5268,2015,7073037,1,0,33074337,1,1,11
1,국제시장,윤제균,씨제이이앤엠(주),A,12/17/2014,winter,개봉영화,장편,한국,966,...,9.272091,1143,2014,0,0,0,51592007,1,0,16
2,킹스맨 : 시크릿 에이전트,매튜 본,이십세기폭스코리아(주),B,2/11/2015,winter,개봉영화,장편,미국,706,...,8.960784,918,2015,7163,1,0,6557445,1,1,12
3,쥬라기 월드,콜린 트레보로우,유니버설픽쳐스인터내셔널 코리아(유),B,6/11/2015,summer,개봉영화,장편,미국,1290,...,8.337789,1945,2015,23,0,1,1472533,1,1,3
4,조선명탐정 : 사라진 놉의 딸,김석윤,(주)쇼박스,C,2/11/2015,winter,개봉영화,장편,한국,811,...,8.172131,610,2015,0,1,0,58897340,1,0,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
920,프란치스코 교황 : 맨 오브 히스 워드,빔 벤더스,"㈜영화사 백두대간,영화사 풀",D,11/21/2019,autumn,개봉영화,장편,기타,54,...,9.600000,10,2019,0,0,1,0,1,0,0
921,아이리시맨,마틴 스코세이지,판씨네마(주),D,11/20/2019,autumn,개봉영화,장편,미국,68,...,8.870588,85,2019,94750,0,1,340008,1,1,5
922,빅 위시,카를로스 구티에레스 메드라노,(주)박수엔터테인먼트,D,10/30/2019,autumn,개봉영화,장편,기타,336,...,6.500000,4,2019,0,0,0,0,1,0,0
923,너를 만난 여름,장적사,"오드,(주)홈초이스",D,10/16/2019,autumn,개봉영화,장편,기타,174,...,8.428571,63,2019,0,0,0,0,1,0,0
924,100일 동안 100가지로 100퍼센트 행복찾기,플로리안 데이비드 핏츠,(주)영화사 진진,D,9/12/2019,autumn,개봉영화,장편,기타,37,...,8.962963,27,2019,0,0,0,0,1,0,0

In [295]:
final_df.to_csv('final_df_11.csv')

In [297]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 925 entries, 0 to 924
Data columns (total 30 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   title                 925 non-null    object
 1   director              925 non-null    object
 2   distributor           925 non-null    object
 3   distributor_group     925 non-null    object
 4   release_date          925 non-null    object
 5   release_season        925 non-null    object
 6   release               925 non-null    object
 7   form                  925 non-null    object
 8   nation                925 non-null    object
 9   screen                925 non-null    int64
 10  rev_nationwide        925 non-null    float64
 11  aud_nationwide        925 non-null    int64
 12  rev_seoul             925 non-null    int64
 13  rev_seoul.1           925 non-null    int64
 14  genre                 925 non-null    object
 15  rate                  925 non-null    object
 16  type                  925 non-null    object
 17  expert_rating         925 non-null    float64
 18  starring_actors       925 non-null    object
 19  running_times         925 non-null    int64
 20  audience_rating       925 non-null    float64
 21  rating_audiences      925 non-null    int64
 22  realease_year         925 non-null    int64
 23  director_power        925 non-null    int64
 24  sequel                925 non-null    int64
 25  original              925 non-null    int64
 26  actor_power           925 non-null    int64
 27  director_count        925 non-null    int64
 28  director_movie_count  925 non-null    int64
 29  actor_movie_count     925 non-null    int64
dtypes: float64(3), int64(14), object(13)
memory usage: 216.9+ KB

In [243]:
# for i, row in compare_df2_sep.iterrows():
#     if float(row['개봉일'][:4]) != row['개봉일_int']:
#         print(i)

In [242]:
# compare_df2_sep.info()